### ISSUE TITLE
vst for C4 synth

### ISSUE THREAD

**Issue by gabrielle-ohlson** [MichaelMCE/TeensyC4Synth#1]
would be really cool to see if some of your code could be used to build a vst for the c4!  I'm pretty new to synth programming so not sure where one would start, but would love some recommendations if that's something you might know about!
(currently looking into adapting some sound matching deep learning models to work with the c4 synth)

**Comment by MichaelMCE** [comment]
For a VST C4 controller then it is absolutely possible, but I would use the [Sa-C4](https://github.com/MichaelMCE/Sa-C4) codebase for this, as this is intended to drive the pedal where the desktop is the host. [TeensyC4Synth ](https://github.com/MichaelMCE/TeensyC4Synth) is intended as an embedded host, which would be unsuitable for this task.  
As for development, I can't pretend to know anything abut VST from development point of view, is there an SDK available? 

As a C4 signal processor/emulator, then no, neither of these two projects would be suitable.
