### ISSUE TITLE
More preset control values please

### ISSUE THREAD

**Issue by MickeyGentry** [MichaelMCE/TeensyC4Synth#2]
Request not an issue…

I’m planning on using this library (thanks!) to attempt morphing from one preset to another. As I don’t have all the pieces yet it would be helpful if you could print out a couple more preset control values lists. 

Thanks for whatever you can do.

**Comment by MichaelMCE** [comment]
Have a look at [Sa-C4](https://github.com/MichaelMCE/Sa-C4), which is TeensyC4Synth but for a Desktop as host through a command line application.
With the above, to print the control values of preset 3 use: sa-c4.exe --preset 3

**Comment by MickeyGentry** [comment]
Thanks for getting back.

I did see that and was excited to try it but I don’t have a Windows machine
anymore. No worries, I also found a Mac app Sysex Librarian which may do
something similar.
