### ISSUE TITLE
A Couple Questions

### ISSUE THREAD

**Issue by MickeyGentry** [MichaelMCE/TeensyC4Synth#3]
This is not an issue. I'm starting a new Teensy project implementing your library. I don't see anywhere that sets which RX/TX pins should be communicating with the C4. I'm using a 4.1 and there are 8 potential sets.

Also I'm using PlatformIO/VSCode and `printf` doesn't seem to do anything. Not sure if you have any insights but I thought I would throw it out there.

Thanks for the library and any insights.

**Comment by MichaelMCE** [comment]
That's fine. I responded here: https://forum.pjrc.com/index.php?threads/usb-driver-for-sourceaudio-c4-synth-pedal.72679/
